
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tradingdb
      POSTGRES_USER: tradinguser
      POSTGRES_PASSWORD: trading_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://tradinguser:trading_pass@postgres:5432/tradingdb
      PYTHONPATH: /app
    volumes:
      - ./:/app

volumes:
  postgres_data: